<?php

namespace AppBundle\Repository;
use AppBundle\Entity\Imagen;
/**
 * ImagenRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImagenRepository extends \Doctrine\ORM\EntityRepository
{
    public function listarAll()
    {
   
        $qb = $this->createQueryBuilder()
            ->leftJoin('i.producto', 'pro')
            ->addSelect('pro');

        $query = $qb->getQuery();
       // var_dump($query->getDQL());die;

        return $query->execute();

    }
}
