<?php

namespace AppBundle\Repository;
use AppBundle\Entity\Tipo;

/**
 * TipoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipoRepository extends \Doctrine\ORM\EntityRepository
{
    public function listarCategoriasConTipos()
    {
        $consulta = $this->getEntityManager()->createQuery(
            'SELECT c.nombre as categoria, t.nombre
            FROM AppBundle\Entity\Categoria c
            left join AppBundle\Entity\Tipo t
            where c.id=t.categoriaId'
            
        );
            $valor = $consulta->getResult();
        return $valor;

    }
}
